### ISSUE TITLE
Example fails on Windows10

### ISSUE THREAD

**Issue by draptik** [ralfw/csrun#18]
Following the instructions, I unzipped the downloaded file, switched to the unzipped directory, and ran the following command:
```
Patrick@RAVEN C:\Users\Patrick\Downloads\csrun
$ .csrun\csrun.exe example.csrun

*** Compiler Errors ***
- example.csrun-4,19: Error: Unexpected character '$'
```

My Windows10 system has .NET 4.5.x and 4.7.1 installed (and dotnet core, but that should not be relevant here, as far as I understand).

Let me know if you need further infos concerning my setup.

**Comment by ralfw** [comment]
Thx! I guess I'm happy! :-) Because if this error shows up then my chance was effective. The bug seems to be fixed.

What you're running into is a different problem. Your compiler seems to not support C# 7.0 because it stumbles over the string comprehension in `Console.WriteLine($"{a}+{b}={r}");`.

Replace that line with `Console.WriteLine("{0}+{1}={2}", a,b,r);` and it should work.

Pls let me know if I'm right and you finally see the expected colorful output ;-)

**Comment by ralfw** [comment]
Oh, no, wait! Although it's good to know your compiler chokes on the syntax and that needs to be fixed, I now see you did not run the proper command. Sorry.

You need to start _csrun_ like this: `.csrun\csrun.exe watch -f example.csrun`

The bug I tried to fix only appears in watch mode, i.e. when _csrun_ is run as a background process. But first fix the syntax problem - and then, please, try again with the correct command.

**Comment by draptik** [comment]
Replacing the `Console.WriteLine` and calling `csrun.exe` with `watch` works on Windows10:

![image](https://user-images.githubusercontent.com/313058/42862374-83fbf7d2-8a5f-11e8-92a9-9420136d02d5.png)
